apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: wordpress
  install:
    createNamespace: true
  chart:
    spec:
      chart: wordpress
      version: '19.2.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
